hackathon/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
	path('', include('project.urls')),
    path('admin/', admin.site.urls),
]
"""
if settings.DEBUG
	urlpatters+=[
		url(r'^Demo/(?P<path>.*)$',serve,{
				'document_root': settings.MEDIA_ROOT,
			})
	]
"""

project/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from . import api

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^landing/?$', views.landing, name='landing'),
    
    url(r'^login/?$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/?$', views.logout_view, name='logout'),
    url(r'^signup/?$', views.signup, name='signup'),
    url(r'^chat/?$', views.chat, name='chat'),
    url(r'^ajax/chat/?$', views.broadcast),


    #API
    url(r'^testFunc1/?$', api.testFunc1, name='testFunc1'),
    url(r'^testFunc2/?$', api.testFunc2, name='testFunc2'),
    url(r'^forceGroups/?$', api.forceGroups, name='forceGroups'),
    url(r'^accept/?$', api.accept, name='accept'),
    url(r'^decline/?$', api.decline, name='decline'),
    url(r'^getNextMatch/?$', api.getNextMatch, name='getNextMatch'),
    url(r'^loadData/?$', api.loadData, name='loadData'),
    url(r'^event/?$', api.event, name='event'),
    url(r'^addevent/?$', api.addEvent, name='addevent'),
    url(r'^updateProfile/?$', api.updateProfile, name='event'),
    url(r'^rejectGroup/?$', api.rejectGroup, name='event'),
    
]

project/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import random, string

import os
from django.core.validators import int_list_validator

# Create your models here.


class Graph(models.Model):
	def __str__(self):
		return("Nodes: " + str(self.node_set.all()) + " Edges: " + str(self.edge_set.all()))


class Event(models.Model):
	def __str__(self):
		return str(self.id)

	name = models.TextField(max_length=50)
	description = models.TextField(max_length=200)
	group_size = models.IntegerField()
	owner = models.IntegerField( default=0)
	#not actually checked for uniqueness, pls fix
	addCode = models.CharField(max_length=10)

	customInfo = models.TextField(max_length=2000, default="{}")

	di = models.OneToOneField(
		Graph,
		on_delete=models.CASCADE,
		related_name = 'di',
	)
	
	undi = models.OneToOneField(
		Graph,
		on_delete=models.CASCADE,
		related_name = 'undi',
	)
	

#Edge (a,b)
class Edge(models.Model):
	a = models.IntegerField()
	b = models.IntegerField()

	graph = models.ForeignKey(Graph, on_delete=models.CASCADE)

	def __str__(self):
		return (str(self.a) + ", " + str(self.b))

	def tuple(self):
		return (self.a, self.b)

#Node just holds the user id
class Node(models.Model):
	userId = models.IntegerField()
	graph = models.ForeignKey(Graph, on_delete=models.CASCADE)

	def __str__(self):
		return(str(self.userId))

#this is the user profile
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	name = models.TextField(max_length=30, blank=True,null=True)
	bio = models.TextField(max_length=500,blank=True,null=True)
	contactInfo = models.TextField(max_length=60, blank=True,null=True)

	age = models.IntegerField(blank=True,null=True)
	pic = models.ImageField(upload_to = 'static/uploads/', default = 'static/uploads/no-img.jpg')


	@receiver(post_save, sender=User)
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Profile.objects.create(user=instance)

	@receiver(post_save, sender=User)
	def save_user_profile(sender, instance, **kwargs):
		instance.profile.save()

#this is the profile tied to each event
class EventProfile(models.Model):
	# using foreignkeys because I'm a good boy
	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	event = models.ForeignKey(Event, on_delete=models.CASCADE)

	#store as JSON
	customInfo = models.TextField(max_length=2000, default="{}")

#the much-feared manyToMany
class Group(models.Model):
	event = models.ForeignKey(Event, on_delete=models.CASCADE)
	users = models.ManyToManyField(EventProfile)
	title = models.TextField(max_length=50,blank=True,null=True)
	uniqueHash = models.TextField(max_length=10)
	customInfo = models.TextField(max_length=2000, default="{}")

class GroupVote(models.Model):
	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	group = models.ForeignKey(Group, on_delete=models.CASCADE)
	vote = models.IntegerField(blank=True,null=True)

project/forms.py
from django.forms import ModelForm
from django import forms
from .models import Event, Profile

class EventForm(ModelForm):
	class Meta:
		model = Event
		fields = ['name', 'group_size', 'description']

class ProfileForm(forms.Form):
	name = forms.CharField()
	bio = forms.CharField()
	pic = forms.ImageField(required=False)
	contactInfo = forms.CharField()

project/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from pusher import Pusher
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm

pusher = Pusher(app_id=u'694776', key=u'4105ec1d8d985dcf27bf', secret=u'1cf25393f1f636e8dc3e' ,cluster=u'us2')


def index(request):
    print(request.user)
    if not request.user.is_authenticated:
        return render(request, 'project/landing.html')
    return render(request, 'project/index.html')

def landing(request):
    if request.user.is_authenticated:
        return redirect('index');  
    return render(request, 'project/landing.html')

@login_required(login_url='/login/')
def chat(request):
	channel = Search.getUserGroupInEvent(request.user.id, 1)
	return render(request, "project/chat.html", {'channel': channel})

@csrf_exempt
def broadcast(request):
	pusher.trigger(u'a_channel', u'an_event', {u'name': request.user.username, u'message': request.POST['message']})
	return HttpResponse("done");

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('index')
	else:
		form = UserCreationForm()
	return render(request, 'registration/signup.html', {'form': form})

def logout_view(request):
	logout(request)
	response_data = {}
	response_data['success'] = True
	return redirect('index')	#all of these functions are returning this JSONresponse because
								#it makes it easy to confirm delivery on the client-side

project/templates/base.html
<!-- development version, includes helpful console warnings -->
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
<script
              src="https://code.jquery.com/jquery-3.3.1.min.js"
              integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
              crossorigin="anonymous"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'project/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'project/sidebar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'project/ripple.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'project/favicon.ico' %}"/>
<script type="text/javascript" src="static/project/popper.min.js"></script>
<script type="text/javascript" src="static/project/bootstrap.min.js"></script>
{% block head %}{% endblock %}
</head>
<body>

<div id="vue-div" v-show=false>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'project/logo.png' %}" style="max-width: 200px;"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
      </li>
      {% endif %}
      <li style="float: right;">
      	<a class="nav-link" > Current user: {{ user.get_username }} </a>
      </li>
    </ul>
  </div>
</nav>



    {% block content %}{% endblock %}

</div>

</body>
</html>

project/templates/project/chat.html
{% extends 'base.html' %}
    {% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="//js.pusher.com/4.0/pusher.min.js"></script>
    <script type="text/javascript" src="../../static/project/chatscript.js"></script>
    <link rel="stylesheet" href="../../static/project/chat.css"/>
    {% endblock %}
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <span class="glyphicon glyphicon-comment"></span> Chat
                        </div>
                        <div class="panel-body">
                    <!-- ul element holding chat messages -->
                            <ul class="chat" id="chat">
                            </ul>
                        </div>
                        <div class="panel-footer">
                            <div class="input-group">
                <!-- text imput fot the messages to be typed into -->
                                <input id="btn-input" class="form-control input-sm" placeholder="Type your message here..." type="text">
                                <span class="input-group-btn">
                <!--- send button for the chat box -->
                                    <button class="btn btn-warning btn-sm" id="btn-chat">
                                        Send</button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

project/templates/project/event.html
{% extends 'base.html' %}

{% block content %}
  <h2>Create Event</h2>
  <form action='/event/' method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit Event</button>
  </form>
{% endblock %}

project/templates/project/index.html
{% extends 'base.html' %}

{% block title %}Groupr{% endblock %}
{% block head %}<script type="text/javascript" src="static/project/main.js"></script> 


{% endblock %}
{% block content %}

<div class="container">

    <transition name="fade" v-if="loading">
        <img src="static/project/loading.svg" class="loadingIndicator">
    </transition>

	<div class="row" id="website" v-if="page_loaded">

		<div class=" col-md-3 col-xl-2 sidenav" v-show="logged_in">
            <div style="padding-left: 30px;">
                <br>
                <div class="btn-group dropright">
                  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Join Event
                </button>
                <div class="dropdown-menu">
                    <form action='/addevent/' method="post">
                        {% csrf_token %}
                        <input type="text" class="form-control" placeholder="Event Code" name="code" autofocus="">
                    </form>
                </div>
            </div>
            <br> <br>
            <div class="btn-group dropright">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Create Event
            </button>
            <div class="dropdown-menu">
                <form action='/event/' method="post">
                    {% csrf_token %}
                    <input type="text" class="form-control" placeholder="Event Name" name="name" autofocus="">
                    <input type="text" class="form-control" placeholder="Event Description" name="description">
                    <input type="text" class="form-control" placeholder="Group Size" name="group_size">
                    <input type="submit" style="display: none;">
                </form>
            </div>
        </div>
        <br> <br>


        <h3>Events</h3>

        <span v-for="(e, i) in events" :key='i'>
            <a href='#' v-bind:class="{active: (i == curr_event && !edit_profile)}" v-on:click="changeEvent(i, false)">${e.name}</a>
        </span>
        <p>----------</p>
        <span><img :src="userData.image" class="rounded-circle mt-2" style=" width: 50px; height: 50px; margin-left: 3em;"> <h3><a href="#" v-bind:class="{active: edit_profile}" v-on:click="toggleEditMode"> Edit Profile</a></h3></span>
        <span><h3></h3></span>
    </div>
    <br><br><br><hr><br>

</div>

<br><br>


<div class="col-md-9 col-xl-8 offset-xl-1" id="mainPage">
    <br><br>
    <div v-if="edit_profile" class="col-md-8">
        <h2><center>Edit Profile</center></h2>
        <br><br>
        <div v-show="userData.bio == null" class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Welcome to Groupr!</strong> Why don't you add some basic info, so that we can get started?
        </div>
        <h3>Basic Info:</h3>


        <br>
        <form action='/updateProfile/' method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name form-control">Display Name</label>
                <input type="text" class="form-control" placeholder="Your Display Name" name="name" id="id_name" autofocus="" v-bind:value="userData.name">
            </div>
            <div class="form-group">
                <label for="id_bio form-control">Bio</label>
                <textarea rows="4" id="id_bio" class="form-control" placeholder="Your bio" name="bio" v-bind:value="userData.bio"> </textarea>
            </div>
            <div class="form-group">
                <label for="id_contact form-control">Phone/email (This will be released to your group after it is formed)</label>
                <input type="text" class="form-control" placeholder="Contact Info" name="contactInfo" id="id_contact" autofocus="" v-bind:value="userData.contactInfo">
            </div>
            <div class="fileUpload btn btn-lg btn-primary">
                <span v-html="inputFileName"> </span>
                <input id="id_pic" type="file" class="file-input upload" name="pic" @input="fileName = $event.target.value">
            </div>
            <input type="submit" class="btn btn-lg btn-success" value="Save">
        </form>

    </div>
    <div v-else>
        <center>
            <span v-if="curr_event != -1">
                <h1> ${events[curr_event].name}  <small>${events[curr_event].description}</small></h1>
                <hr>
                <br>
                <span v-if="events[curr_event].isIn">

                    <span v-if="typeof events[curr_event].group != 'undefined'">
                        <h4>Here is your group:</h4>
                        <br>
                        <div class="container">
                            <center>
                        <div class="row">
 
                                <div v-for="user in events[curr_event].group.users" class=" col-md-6 col-xl-4" >
                                    <div class=" card mx-2 my-4">
                                <h4 class="card-header">${user.name}<span v-if="user.id == userData.id" class="text-muted"> <small>(You!)</small></span></h4>
                                <center>
                                <img v-bind:src="user.image" class="rounded-circle mt-2" style=" width: 200px; height: 200px;">
                            </center>
                                <div class="card-body">
                                    <p class="card-text">${user.bio}</p>
                                </div>
                                <h6>${user.contactInfo}</h6>
                            </div>
                            </div>
                            </div>
                        </center>
                        </div>
                            
                            
                        
                        <br>
                        <h5 class="text-warning" v-show="confirmReject">Are you sure? <br>This will Destroy the group for everyone!</h5>
                        <button type="button" class="btn btn-primary btn-lg" v-on:click="rejectGroup">Reject Group</button>

                    </span>

                    <span v-else-if="suggested_usr.name != ''" id="suggestedUserView">
                        <div class="row" >
                            <div class="col-md-6">
                                <img v-bind:src="suggested_usr.image" class="img img-fluid rounded-circle" style=" width: 300px; height: 300px;">
                            </div>
                            <div class="col-md-6">
                                <br>
                                <h3>${suggested_usr.name} </h3>
                                <br>
                                <h5 style="line-height: 28px;">${suggested_usr.bio}</h5>
                            </div>
                        </div>
                        <br>
                        <button type="button" class="btn acceptdecline btn-primary btn-lg" v-on:click="decline">decline</button>               
                        <button type="button" class="btn acceptdecline btn-primary btn-lg" v-on:click="accept">accept</button>

                    </span>

                    <span v-else>
                        <h3>It looks like you've rated everyone in this event!</h3>
                    </span>

                </span>
                <span v-else>
                    <h3>You are not currently a user in this Event.</h3>
                    <form action='/addevent/' method="post">
                            {% csrf_token %}
                            <input type="text" class="form-control" :value="events[curr_event].addCode" name="code"  style="display: none;">
                            <input type="submit" value="Join This Event" class="btn btn-secondary">
                        </form>
                </span>
                <span v-if="events[curr_event].isOwner">
                    <br><hr><br><br><hr><br>
                    <h2>You are the owner of this event. </h2>
                    <h2>Add Code:  ${events[curr_event].addCode}</h2>
                    <br>
                    <button type="button" class="btn btn-primary btn-lg" v-on:click="forceGroups">Force Group Creation</button>
                </span>
            </span>

            <span v-else>
                <h1> You Don't Have Any Events </h1>
                <h3>Why don't you create an event, or join one?</h3>
            </span>

            <br><br><br><br><br>
     </center>
 </div>
</div>
</div>
</div>
{% endblock %}

project/templates/project/landing.html
<!-- development version, includes helpful console warnings -->
<!DOCTYPE html>
<html>
<head>
    <title>Groupr</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script
              src="https://code.jquery.com/jquery-3.3.1.min.js"
              integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
              crossorigin="anonymous"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'project/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'project/sidebar.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'project/favicon.ico' %}"/>
<script type="text/javascript" src="{% static 'project/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'project/bootstrap.min.js' %}"></script>
</head>
<body>

<div id="vue-div" v-show=false>

    <div class="container">
        <div class="row">
            <div class="jumbotron" style="width: 100%;">
                
                <center>
                    <div style="max-width: 1000px;">
                        <img src="{% static 'project/logo-big.png' %}" class="img-fluid">
                    </div>
                    
                </center>
                <br><br>
                <div class="col-md-8 offset-md-2">
                    <h1 class="center">Groupr will help you find your team.</h1>
                <center>
                    <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/BPk9gmIsrC0" frameborder="0" allow="accelerometer; autoplay; encrypted-media;picture-in-picture" allowfullscreen></iframe>
                </center>
                <h4 class="center">Choose whom you'd like to work with, and let our algorithms do the rest.</h4>
                </div>

                

        </div>
        </div>

        <div class="col-md-6 offset-md-3">
            <br><br>
                <center>
                <h2>Sign up</h2>
                  <form action='/signup/' method="post">
                        {% csrf_token %}
                        <div class="row">
                            
                            <div class="col-md-6" style="padding-right: 30px;">
                                <label for="id_username">Username: </label>
                                <br>
                                <input type="text" name="username" maxlength="150"  required="" id="id_username">

                                <br><br>

                                <label for="your_name">Display Name: </label>
                                <br>
                                <input id="your_name" type="text" name="your_name">
                            </div>

                            <div class="col-md-6">
                                <label for="id_password1">Password:</label>
                                <br>
                                <input type="password" name="password1" required="" id="id_password1">

                                <br><br>

                                <label for="id_password2">Password confirmation:</label>
                                <br>
                                <input type="password" name="password2" required="" id="id_password2">
                                
                            </div>
                            <br>
                        </div>
                        <br>
                        <input type="submit" value="Sign Up" class="btn btn-primary btn-lg">
                  </form>
            </center>
        </div>
        <div class="col-md-6 offset-md-3">
            <br><br><br>
            <center>

                <div class="btn-group dropdown loginbutton">
                  <button type="button" id="yeep" class="btn btn-secondary btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Log In
                </button>
                <div class="dropdown-menu">
                    <form action='/login/' method="post">
                        {% csrf_token %}
                        <input type="text" id="signInField" class="form-control" placeholder="Username" name="username">
                        <input type="password" class="form-control" placeholder="Password" name="password">
                        <input type="submit" style="display: none;">
                    </form>
                </div>
            </div>
            </center>
            
        </div>
        <div class="row about">
            <div class="col-md-6 offset-md-3">
                <center><h1>About Groupr</h1></center>
                <br>
            <p>After signing up, you can create a basic profile and create an Event. An "Event" is any large group of people that you would like to form subgroups of. For example, a classroom or a Hackathon Event. The owner of the Event will be given an invite code. Once users have joined the event, they will be able to see other users, and start choosing if they want to work with them. Groups will be formed and can be discarded if the group decides to do so.</p>
            <br>
            <br>
            <center><h4>For questions or inquiries, please email usegroupr@gmail.com</h4></center>
            </div>
            
        </div>


</div>
</div>

                <script type="text/javascript">
                    console.log("asfsa")
                    $("#yeep" ).click(function() {
                        console.log("AFASDSAGADJFSA")
                      $('#signInField').focus().select()
                    });
                </script>


</body>
</html>